### ISSUE TITLE
Composer require error

### ISSUE THREAD

**Issue by sevmardi** [LinearSoft/laravel-activitylog-backport#1]
Hey! I am trying to pull this package, but I am getting the following error. 
`[InvalidArgumentException]                                                                            
Could not find package linearsoft/laravel-activitylog at any version for your minimum-stability (st   
  ⚠  1 warning  able). Check the package spelling or your minimum-stability`

Any ideas? 

**Update**: I have downloaded the zip and copy/past it into the vendor. It worked.

**Comment by CrashSensei** [comment]
My apologies.  There was mistake with the documentation (now fixed).  Please run the following command to do the install
`composer require linearsoft/laravel-activitylog-backport`

**Comment by sevmardi** [comment]
Hi! Do I still need php 7  server setup to install this backport? 

I get `Could not find package linearsoft/laravel-activitylog-backport at any version matching your PHP version 5.5.9.0`

Ideas?

**Comment by CrashSensei** [comment]
No you do not need PHP7.  You do, however, need PHP 5.6. This package is not compatible with PHP 5.5.

**Comment by sevmardi** [comment]
Thanks!
